name: Update Credly Badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    env:
      TARGET_SIZE: '120'   # change this to any pixel size you want
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate badges (pemtajo/badge-readme)
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: javier-pestano-ron

      - name: Normalize Credly badge URLs and sizes
        run: |
          set -e
          if [ ! -f README.md ]; then
            echo "README.md not found, exiting"
            exit 0
          fi

          python3 - <<'PY'
          import re, os
          path = 'README.md'
          txt = open(path, 'r', encoding='utf-8').read()

          # 1) Remove any /size/{NxN} segment from Credly URLs
          txt = re.sub(r'/size/\d+x\d+', '', txt)

          # 2) Replace existing width/height numeric values (single or double quotes)
          target = os.environ.get('TARGET_SIZE', '120')
          txt = re.sub(r'width=(["\'])\d+\1', f'width="{target}"', txt)
          txt = re.sub(r'height=(["\'])\d+\1', f'height="{target}"', txt)

          # 3) Add width/height to Credly <img> tags that don't have them
          def add_wh(match):
              tag = match.group(0)
              if re.search(r'\bwidth=|\bheight=', tag):
                  return tag
              if tag.endswith('/>'):
                  return tag[:-2] + f' width="{target}" height="{target}" />'
              else:
                  return tag[:-1] + f' width="{target}" height="{target}" >'

          txt = re.sub(r'<img\b[^>]*src=(["\'])https://images\.credly\.com/images/[^>]*\1[^>]*>', add_wh, txt)

          open(path, 'w', encoding='utf-8').write(txt)
          print("README normalized")
          PY

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # only commit & push if there are changes
          git diff --staged --quiet || (git commit -m "Update Credly badges to ${TARGET_SIZE}px and use full-size images" && git push)
