name: Update Credly Badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: javier-pestano-ron

      - name: Fix badge image URLs
        run: |
          sed -i 's|/size/80x80||g' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Fix badge image URLs to full size" || echo "No changes to commit"
          git push
